baseURL = 'https://molsen.ca/'
languageCode = 'en-ca'
title = 'Mike Olsen'

[params]
  description = "Thinking about AI, professional accountability, and the future of technical work."
  author = "Mike Olsen"
  # Kit (formerly ConvertKit) form ID
  convertkit_form_id = "8922490"
  linkedin_url = "https://www.linkedin.com/in/mikealolsen/"

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
